name: Go
on:
  workflow_dispatch: null
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    # Run full test once a day
    - cron: '0 0 * * *'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/setup-go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version: 1.21.3
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Required: the version of golangci-lint is required
          # and must be specified without patch version:
          # we always use the latest patch version.
          version: v1.54.1
          install-mode: "binary"
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true
      - name: Show GoReleaser version
        run: goreleaser --version
      - name: Build
        run: make build
      - name: Quick Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make test-short
        if: ${{ github.event_name == 'pull_request' }}
      - name: All Test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          # DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          # DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: make test
        if: ${{ github.event_name == 'schedule' }}
      # Codecov should only be updated if make test is executed
