name: Publish Release Assets
on:
  workflow_dispatch: null
  release:
    types: [published]
permissions:
  contents: write
  id-token: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache: false
          go-version: 1.21.3
        id: go
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          install-only: true
      - name: Show GoReleaser version
        run: goreleaser --version
      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0.14.3
      - name: GoReleaser
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goreleaser release
